const express = require("express");

const qpaySearch = require("../controllers/SC/multi_county_qpay.controller.js");

const aiken_search = require("../controllers/SC/aiken.controller.js");
const chester_search = require("../controllers/SC/chester.controller.js");
const fairfield_search = require("../controllers/SC/fairfield.controller.js");
const hampton_search = require("../controllers/SC/hampton.controller.js");
const pickens_search = require("../controllers/SC/pickens.controller.js");
const york_search = require("../controllers/SC/york.controller.js");
const florence_search = require("../controllers/SC/florence.controller.js");
const georgetown_search = require("../controllers/SC/georgetown.controller.js");
const richland_search = require("../controllers/SC/richland.controller.js");
const berkeley_search = require("../controllers/SC/berkeley.controller.js");
const greenville_search = require("../controllers/SC/greenville.controller.js");
const greenwood_search = require("../controllers/SC/greenwood.controller.js");
const dorchester_search = require("../controllers/SC/dorchester.controller.js");
const charleston_search = require("../controllers/SC/charleston.controller.js");
const jasper_search = require("../controllers/SC/jasper.controller.js");
const anderson_search = require("../controllers/SC/anderson.controller.js");
const beaufort_search = require("../controllers/SC/beaufort.controller.js");

const route = express.Router();

route.post("/marlboro", qpaySearch.search);
route.post("/union", qpaySearch.search);
route.post("/bamberg", qpaySearch.search);
route.post("/williamsburg", qpaySearch.search);
route.post("/dillon", qpaySearch.search);
route.post("/colleton", qpaySearch.search);
route.post("/calhoun", qpaySearch.search);
route.post("/mccormick", qpaySearch.search);
route.post("/newberry", qpaySearch.search);
route.post("/abbeville", qpaySearch.search);
route.post("/chesterfield", qpaySearch.search);
route.post("/spartanburg", qpaySearch.search);
route.post("/barnwell", qpaySearch.search);
route.post("/allendale", qpaySearch.search);
route.post("/sumter", qpaySearch.search);
route.post("/cherokee", qpaySearch.search);
route.post("/darlington", qpaySearch.search);
route.post("/kershaw", qpaySearch.search);
route.post("/laurens", qpaySearch.search);
route.post("/horry", qpaySearch.search);
route.post("/oconee", qpaySearch.search);
route.post("/lexington", qpaySearch.search);
route.post("/saluda", qpaySearch.search);
route.post("/lancaster", qpaySearch.search);
route.post("/clarendon", qpaySearch.search);
route.post("/lee", qpaySearch.search);
route.post("/edgefield", qpaySearch.search);
route.post("/orangeburg", qpaySearch.search);

route.post("/aiken", aiken_search.search);
route.post("/chester", chester_search.search);
route.post("/fairfield", fairfield_search.search);
route.post("/hampton", hampton_search.search);
route.post("/pickens", pickens_search.search);
route.post("/york", york_search.search);
route.post("/florence", florence_search.search);
route.post("/georgetown", georgetown_search.search);
route.post("/richland", richland_search.search);
route.post("/berkeley", berkeley_search.search);
route.post("/greenville", greenville_search.search);
route.post("/greenwood", greenwood_search.search);
route.post("/dorchester", dorchester_search.search);
route.post("/charleston", charleston_search.search);
route.post("/jasper", jasper_search.search);
route.post("/anderson", anderson_search.search);
route.post("/beaufort", beaufort_search.search);

module.exports = route;